AttributeError: 'Sequence' object has no attribute 'arg'
Hi, thanks for the library!
I just started integrating it and had the above error with the Oracle dialect after passing in a ``Sequence`` object for ``default``.

However, I need to pass in a sequence to simulate an auto-incrementing ID:

```python
id = Column(Integer, default=Sequence('id_seq'), primary_key=True)
```

This fix solves the problem by explicity checking if column.default is a ColumnDefault instance.

What do you think?